apiVersion: apps/v1
kind: Deployment
metadata:
  name: baseball-name-game
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baseball-name-game
  template:
    metadata:
      labels:
        app: baseball-name-game
    spec:
      containers:
      - name: baseball-name-game
        image: localhost:5000/baseball-game:latest
        imagePullPolicy: Never
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: ALSA_CARD
          value: "Generic"
        - name: ALSA_DEVICE
          value: "default"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: dev-snd
          mountPath: /dev/snd
        - name: asound-config
          mountPath: /etc/asound.conf
          subPath: asound.conf
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: dev-snd
        hostPath:
          path: /dev/snd
      - name: asound-config
        configMap:
          name: asound-config 