apiVersion: apps/v1
kind: Deployment
metadata:
  name: baseball-name-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baseball-name-game
  template:
    metadata:
      labels:
        app: baseball-name-game
    spec:
      containers:
      - name: baseball-name-game
        image: baseball-game:latest
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: app-volume
          mountPath: /app
      volumes:
      - name: app-volume
        emptyDir: {} 