apiVersion: apps/v1
kind: Deployment
metadata:
  name: novnc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novnc
  template:
    metadata:
      labels:
        app: novnc
    spec:
      containers:
      - name: novnc
        image: theasp/novnc:latest
        ports:
        - containerPort: 8080
        env:
        - name: VNC_SERVER
          value: "baseball-name-game-service:5900"
        - name: VNC_PASSWORD
          value: "baseball" 